export const enum KEYS {
  // C = 'C',
  // X = 'X',
  // Z = 'Z',
  // Y = 'Y',
  // A = 'A',
  // G = 'G',
  // L = 'L',
  // F = 'F',
  // D = 'D',
  // B = 'B',
  DIGIT_0 = '0',
  DELETE = 'DELETE',
  UP = 'ARROWUP',
  DOWN = 'ARROWDOWN',
  LEFT = 'ARROWLEFT',
  RIGHT = 'ARROWRIGHT',
  ENTER = 'ENTER',
  BACKSPACE = 'BACKSPACE',
}